version: '3.7'

networks:
  dev-net:
    external: true
  test-net:
    external: true
  exp-net:
    external: true
    

secrets:
  h5p_db_dba_password:
    external: true
  h5P_password:
    external: true


services:
  h5p-db:
    image: 192.87.106.18:56001/postgres:0.1          
    volumes:
      - /mnt/nfs/nfsdlo/$STACK_NETWORK/$STACK_SERVICE/$STACK_VERSION/data:/var/lib/postgresql/data
    secrets:
      - h5p_db_dba_password
    environment:
      POSTGRES_DB:h5p 
      POSTGRES_USER: h5p 
      POSTGRES_PASSWORD_FILE: /run/secrets/h5p_db_dba_password
      # POSTGRES_PASSWORD: password
    networks:
      - $STACK_NETWORK
      
  h5p:
    image: 192.87.106.18:56001/h5p:0.1
    hostname: $STACK_DOMAIN
    secrets:
      - h5p_db_dba_password
      - h5p_password
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: h5p-db
      DB_DATABASE: h5p
      DB_USER: h5p
      DB_SCHEMA: public
      DB_PASSWORD_FILE: /run/secrets/h5p_db_dba_password
      #DB_PASSWORD: password
    networks:
      - $STACK_NETWORK
    ports:
      - $STACK_PORT:80
    depends_on:
      - postgres
