version: '3.7'

networks:
  dev-net:
    external: true
  test-net:
    external: true
  exp-net:
    external: true

secrets:
  h5p_db_dba_password:
    external: true

services:
  h5p_db:
    container_name: h5p_db
    image: 192.87.106.18:56001/postgres:0.1
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
      restart_policy:
        condition: any
    environment:
      POSTGRES_USER: h5p_user
      POSTGRES_PASSWORD: dontusethis
      #POSTGRES_PASSWORD_FILE: /run/secrets/h5p_db_dba_password
      POSTGRES_DB: h5p
      POSTGRES_INITDB_ARGS: "--data-checksums"
    secrets:
      - h5p_db_dba_password  
    networks:
      - $STACK_NETWORK
    volumes:
      # - /var/lib/postgresql/data
      - /mnt/nfs/nfsdlo/$STACK_NETWORK/$STACK_SERVICE/$STACK_VERSION/psqldata:/var/lib/postgresql/data


